name: Copy and Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  copy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.5

      - name: Clone original repository
        uses: actions/checkout@v2.3.5
        with:
          repository: actions-hub/gcloud
          ref: ${{ github.ref }}
          path: gcloud

      - name: "Build Docker: Latest tag"
        uses: elgohr/Publish-Docker-Github-Action@master
        if: github.ref == 'refs/heads/master'
        with:
          name: patrickdappollonio/github-action-gcloud
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: gcloud/Dockerfile
          context: gcloud/
          tags: latest

      - name: Get the version
        id: get_version
        if: github.ref != 'refs/heads/master'
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: "Build Docker: Release tag"
        uses: elgohr/Publish-Docker-Github-Action@master
        if: github.ref != 'refs/heads/master'
        with:
          name: patrickdappollonio/github-action-gcloud
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: gcloud/Dockerfile
          context: gcloud/
          tags: ${{ steps.get_version.outputs.VERSION }}
