name: Copy and Release

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  copy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.0.0

      - name: Clone original repository
        uses: actions/checkout@v2.0.0
        with:
          repository: actions-hub/gcloud
          ref: ${{ github.ref }}
          path: gcloud

      - name: Build Docker: Latest tag
        uses: elgohr/Publish-Docker-Github-Action@master
        if: github.ref == 'refs/heads/master'
        with:
          name: patrickdappollonio/github-action-gcloud
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: gcloud/Dockerfile
          context: gcloud/
          tags: latest

      - name: Build Docker: Release tag
        uses: elgohr/Publish-Docker-Github-Action@master
        if: github.ref != 'refs/heads/master'
        with:
          name: patrickdappollonio/github-action-gcloud
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: gcloud/Dockerfile
          context: gcloud/
          tags: ${GITHUB_REF/refs\/tags\//}
